In [1]:
# 1.split this string

s="Hi there Sam!"
output=s.split()
print(output)


['Hi', 'there', 'Sam!']


In [3]:
# 2. Use .format() to print the following string.

planet="Earth"
diameter=12742

print(" The diameter of the {} is {} kilometers.".format(planet,diameter))

 The diameter of the Earth is 12742 kilometers.


In [4]:
# 3.In this nest dictionary grap the world "hello"

d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


In [7]:
# 4. create an array of 10 zeros
#  create an array of 10 Fives
a=[]
b=[]
for i in range(0,10):
    a.append(0)
    b.append(5)
print(a)
print(b)
    
    


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [8]:
# 5.create an array of all the even integers from 20 to 35

a=[]
start=20
end=35
for i in range(start,end+1):
    if i%2==0:
        a.append(i)
print(a)

[20, 22, 24, 26, 28, 30, 32, 34]


In [11]:
# 6. create a 3*3 matrix with values ranging from 0 to 8

import numpy as np

x=np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#7. Concatinate a and b
a=[1,2,3]
b=[4,5,6]
res=a+b
print(res)



[1, 2, 3, 4, 5, 6]


In [16]:
#8.Create a dataframe with 3 rows and 2 columns

import pandas as pd
data=[['tom',10],['nick',15]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)





   Name  Age
0   tom   10
1  nick   15


In [22]:
#9.Generate the series of dates from 1st jan,2023 to 10th feb,2023

import datetime
import pandas as pd
start = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
end = datetime.datetime.strptime("10-02-2023", "%d-%m-%Y")
date_generated = pd.date_range(start, end)
print (date_generated.strftime("%d-%m-%Y")) 

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


In [26]:
#10.Create 2D list to dataframe

import pandas as pd

lists=[[1,"aaa",22],[2,"bbb",25],[3,"ccc",24]]
df=pd.DataFrame(dt,columns=["d"])
print(df)


<class 'IndentationError'>: expected an indented block after 'for' statement on line 7 (<ipython-input-26-ee941f490123>, line 10)